---
version: '3.7'
services:

  importer:
    image: manticoresearch/importer
    container_name: ${NAMESPACE}-importer
    build:
      context: ./.docker/manticore
      dockerfile: Dockerfile
    ports:
    - "9306:9306"
    - "9313:9312"
    volumes:
    - mt-data:/var/lib/manticore/data
    - ./shared/logs/manticore:/var/log/manticore
    - ./.config/manticore/:/etc/manticoresearch/
    # networks:
    # - internal

  # https://github.com/manticoresoftware/docker
  # mysql -P9306 -h 127.0.0.1 < assets/sql/truncate_sphinx.sql
  manticore:
    image: manticoresearch/manticore:latest
    container_name: ${NAMESPACE}-server
    ports:
    - "9306:9306"
    - "9313:9312"
    volumes:
    - mt-data:/var/lib/manticore/data
    - ./logs/manticore:/var/log/manticore
    - ./manticore.conf:/etc/manticoresearch/manticore.conf

volumes:
  mt-data: