---
version: '3.7'
services:

  importer:
    image: manticoresearch/importer
    container_name: ${NAMESPACE}-importer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - mt-data:/var/lib/manticore/data
    - ./shared/logs/manticore:/var/log/manticore
    - ./.config/manticore/:/etc/manticoresearch/
    - ./manticore-dump.sql:/opt/manticore/data/manticore-dump.sql:ro
    depends_on:
    - manticore
    links:
    - manticore:manticore
    command: ["manticore-test", "--manticore-host=manticore", "--manticore-port=9312", "--parallel-jobs=1"]

  manticore:
    image: manticoresearch/manticore:latest
    container_name: ${NAMESPACE}-server
    ports:
    - "9306:9306"
    - "9313:9312"
    volumes:
    - mt-data:/var/lib/manticore/data
    - ./logs/manticore:/var/log/manticore
    - ./manticore.conf:/etc/manticoresearch/manticore.conf
    command: ["searchd", "--nodetach", "--logdebugvv"]

volumes:
  mt-data: